Repository lenstags/Lenstags, pull requests merged in 2023-01, with the labels that each got.

#36 fix
  pages/explorer/index.tsx
  pages/index.tsx
Labels: bug

#41 Adds gassless txs posts and dispatcher selector
  __mocks__/profileMockData.ts
  components/Profile.tsx
  lib/lens/dispatcher.ts
  lib/lens/post-gasless.ts
  lib/lens/post.ts
  lib/lens/publication-post.ts
  pages/create/index.tsx
Labels: UI, dapp-infrastructure

#63 fix bug
  pages/settings/index.tsx
Labels: bug, UI
